sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

script: mvn verify -Ptest

after_success:
  - docker build -t paukiatwee/budgetapp .
  - docker push paukiatwee/budgetapp

env:
  global:
    secure: E6Px/rHwipg36kfJxyRhalA5HVLDsQFXN2kd1arECFkLQQULJMrKDC3H2J6dSblV5ALMxRe4AoJ/jSfBYOcOwH+1qIkk40bOx1B4LxJrqvkGnbgKmDmYOIaKi0g4Lm4vUo54rDSe/O69m50kPdZn0NQdNmcpCSfGOASwagCaAc0=
